# Generated by Django 3.0.2 on 2020-01-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
